### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by LordMike** [ScottHelme/report-uri-bugs#2]
Make it possible to create a dashboard. It should be possible to enter domains and add them to the list.

You could then
* Show graphs for reports / counters for the last X hours of HPKP and CSP (indicating issues)
* Poll the sites and verify that HPKP, CSP and / or HSTS are enabled
* Create quick links to check HPKP, CSP, SSLLabs etc.
* Monitor SSL expiry and warn on this

**Comment by ScottHelme** [comment]
Customised dashboards is something I've wanted for a long time but would require a little more work than I'd like so has had a lower priority than other tasks. 

I like the idea of some kind of indicator to detect the presence of appropriate headers on sites you collect reports for. 

Quick links sounds like a good idea too.

SSL expiry monitoring is something that I might be addressing soon :-)

**Comment by LordMike** [comment]
While I request right and left, be weary of what you do.. Is report-uri the start of a website compliance manager, or is it a specialized (but do it well) site for HPKP and CSP?

Just my 0.02$ :)

**Comment by ScottHelme** [comment]
I think report-uri.io will be CSP/HPKP for the foreseeable future. Other services may come along that offer different things :)

**Comment by ScottHelme** [comment]
I'm going to close this issue as it's quite broad, I have a few new features in mind that will be coming soon. If you'd like to raise something more specific, please feel free :-)
