### ISSUE TITLE
Report-Only icon

### ISSUE THREAD

**Issue by craigfrancis** [ScottHelme/report-uri-bugs#4]
On the reporting page:

https://report-uri.io/account/reports/csp/

The left hand column always shows "Report Only", where it's displayed in blue when it's Report-Only, or light grey when Enforced.

![Current Preview](https://cloud.githubusercontent.com/assets/1296695/14210390/b0cc2990-f820-11e5-9906-126d4ced2d2d.png)

Maybe this could be changed to have a "Enforced" (maybe in orange)?

![Suggested Preview](https://cloud.githubusercontent.com/assets/1296695/14210485/16837dd8-f821-11e5-998c-e9302ec7f552.gif)

This will fix the problem of only having Enforced reports (where you currently have nothing to compare it to, so it looks like the reports are Report-Only), and it would also help with accessibility (WCAG criteria 1.6) "Color is not used as the only visual means of conveying information"

https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html

**Comment by ScottHelme** [comment]
Thanks for the info Craig.

With the recent update to filter between enforced/report-only, and the default option to filter on enforced, this is a little less clear now. I like the idea of changing the text to read 'Enforced' but will play around with the colour. For a full page of enforced reports, that could be a lot of a negative colour!

The accessibility criteria is also a great point to raise and is why I changed from red/green squares to a tick and cross on the analysers: https://report-uri.io/home/analyse/https%3A%2F%2Fscotthelme.co.uk

![image](https://cloud.githubusercontent.com/assets/5352840/14211256/e8800182-f824-11e5-8bfb-d38d8f471a10.png)

I will get some changes together and update the ticket.

**Comment by craigfrancis** [comment]
Thanks Scott,

And I should note, I'm certainly not a designer, so please don't take any design advice from me (orange probably is a bit too strong).

**Comment by ScottHelme** [comment]
I've pushed a patch for this to test, it should hit live soon. A feature request can be raised if anyone doesn't like my colour choices ;-)

**Comment by ScottHelme** [comment]
This change is now live :-)

**Comment by craigfrancis** [comment]
Looks good to me, thanks Scott :-)
