### ISSUE TITLE
Timezone setting change causes incorrect timestamp to be displayed in reports.

### ISSUE THREAD

**Issue by agarci40** [ScottHelme/report-uri-bugs#6]
I adjusted the timezone setting to make it easier for us to understand when things were happening. After having made the change I saw strange behavior. 

1. Set my timezone to (UTC -07:00) America/Los Angeles.
2. Go to the reports tab. 
3. Hour filter defaults to the correct current hour.
4. Timestamp on the reports does not match the filter and is off by -8 hours. 
5. Switch timezone back to a default of (UTC +01:00)
6. Go back to reports tab
7. Hour filter still defaults to the correct current hour. 
8. Same reports appear, but now with a timestamp that matches the filter.

The real time tab does not appear to work for me at all and events simply appear in the reports tab. Perhaps this is related or not. It could be that this tab only shows enforced reports now?

**Comment by ScottHelme** [comment]
Ok I've spotted the issue here and pushed a patch to the dev site. I will keep an eye on that and maybe push it to test today. If it holds up, it should hit live by the end of the week.

**Comment by ScottHelme** [comment]
Patch now in test.
