### ISSUE TITLE
Please add "none:" to unactionable violations filter

### ISSUE THREAD

**Issue by gwire** [ScottHelme/report-uri-bugs#7]
The most common violations I see (with the unactionable filter on) are `"blocked-uri": "none://rapport-daishi-request-d"` and `"blocked-uri": "none://rapport-daishi-request-f"`. (I don't know what generates these, possibly [IBM Security Trusteer Rapport](http://www-03.ibm.com/software/products/en/trusteer-rapport)?)

Please add `none:` to the unactionable list.

There's no entry for it in the [URI registry](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), and I doubt it will ever be used for non-local purposes.

**Comment by ScottHelme** [comment]
I've added this filter to the test site and it should make it's way to live in a few days.

**Comment by ScottHelme** [comment]
This is now in live, thanks!
