### ISSUE TITLE
Custom Blocked URI filters

### ISSUE THREAD

**Issue by agarci40** [ScottHelme/report-uri-bugs#8]
We get a lot of csp reports. Almost all of them are caused by malware, web browser extensions and what seems to be proxy services.

The most common ones I see have a blocked uri like this.
"http://10.237.69.146:15871"

There are hundreds every minute all with different IP addresses, but most in the reserved address space. Being able to add filters to block these reports would be nice, especially if I can do wildcards like http://*:15871

The only thing these share are the port number which after some googling seems to be the port of a remote filtering server product by websense. Due to the amount of different ones of these I am seeing I think a lot of our visitors are using this software. 

I also see some random sites which I can assume are malware sites showing up. 

There are also quite a few we are getting from extensions for new browsers. Like the microsoft edge browser.

ms-appx-web://
ms-appx-web://microsoft.microsoftedge

I also see a bunch with the blocked URI
http://themes.googleusercontent.com
http://fonts.gstatic.com

These I am assuming are from an extension that caches and loads fonts based on what I searched and read up on.

Not to mention all the random sites that we are definitely NOT introducing on our end:

```
> http://alert.scansafe.net
> http://www.reduxmediia.com
> http://wsaerror.healthpartners.com
> http://air-proxy-4-wcg.corp.capgemini.com:8080
> http://cl4appf.com
> http://www.onclicktop.com
> etc.....
> 
```

As you can tell I am drowning in all of these making the whole thing almost useless at this point. The only solution I see to this is custom filtering rules.

**Comment by ScottHelme** [comment]
The port 15871 seems to be a WebSense block port: http://www.websense.com/support/article/t-kbarticle/Websense-Web-Security-default-ports

I can add ms-appx-web:// to the unactionable CSP violation filter. 

I could possibly add a new field, similar to collect hosts, for defining blocked hosts to drop reports from. 

The main problem I have is that I need to keep the filters suitable for the thousands of sites that use report-uri.io at present. What about a filter to drop reports where the blocked-uri is an IP address and not a hostname? That seems like it could be useful. If you're not expecting to load resources from an IP address on your site it should be a fairly easy filter to know you can enable.

**Comment by LordMike** [comment]
This also seems like a bug in whatever browser the client is using or the
websense product. Unless it's a linked resource that gets blocked?
Must be.

Also. Be warned about just going block-crazy, as that itself defeats some
of the points of CSP reporting.

Mvh.
Michael

**Comment by ScottHelme** [comment]
I think what happens is that the resource/page is redirected to the block page and that triggers the CSP violation with the associated blocked-uri value. For example if you load an image from not-blocked.com which is on the whitelist and it redirects to is-blocked.com which isn't on the whitelist, the load would be blocked and the blocked URI would be is-blocked.com in the report.

All of the filters I implement are optional so can be used at the discretion of the account holder. I do need to provide enough filtering options for everyone to be able to fine tune their incoming reports so they are useful. If I did introduce these filters, they wouldn't affect you unless you enabled them.

**Comment by LordMike** [comment]
This was more of a general thought. I'm curious where the 

    > http://alert.scansafe.net
    > http://www.reduxmediia.com
    > http://wsaerror.healthpartners.com
    > http://air-proxy-4-wcg.corp.capgemini.com:8080
    > http://cl4appf.com
    > http://www.onclicktop.com
    > etc.....
    > 

... come from..

**Comment by agarci40** [comment]
I now realize that there is information missing from my first post. The goal of our reporting is to detect mixed content errors. We switched to have our site use https in the last two weeks so we are using this tool to help us detect the mixed content errors. 

This is a full payload of one of the reports. 
{
    "csp-report": {
        "document-uri": "https://www.experts-exchange.com",
        "violated-directive": "default-src https: 'unsafe-inline' 'unsafe-eval'",
        "effective-directive": "script-src",
        "original-policy": "default-src https: 'unsafe-inline' 'unsafe-eval'; connect-src https: wss:; img-src https: data:; font-src https: data:; report-uri https://ee.report-uri.io/r/default/csp/reportOnly",
        "blocked-uri": "http://10.17.120.59:15871",
        "status-code": 0
    }
}

I think that what I am asking for is more of a filter to stop some of the reports from being displayed, not necessarily drop them all together. I don't everyone to have the same use case as me. Or another option would be to be able to export the reports in a file so I can download and process them. That would also make it easier to share with others in my team.

**Comment by LordMike** [comment]
Ah. This makes more sense. I feared that you had a big problem and were hoping to ignore it. :)
Carry on ;)

**Comment by agarci40** [comment]
Since I need a higher level customization in my reports I decided that I need to implement our own csp endpoint. Using report-uri has helped us a lot in the mean time. Thanks for your work Scott.
